name: Deploy Preview

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: "The Pull request to target for the deploy-preview"
        required: true
        type: text
      authentication:
        description: "The secret to authorize this action run"
        required: true
        type: text

jobs:
  validate_run:
    runs-on: ubuntu-latest
    name: Validate run
    outputs:
      valid_request: ${{ steps.valid_request.outputs.valid }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=valid::${{ inputs.authentication == secrets.AUTH }}"
        id: valid_request
  preview:
    needs: [validate_run]
    if: needs.validate_run.outputs.valid_request == 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo It works!
