name: Deploy Preview

on:
  repository_dispatch:
    types: [deploy_preview]

jobs:
  validate_run:
    runs-on: ubuntu-latest
    name: Validate run
    outputs:
      valid_request: ${{ steps.valid_request.outputs.valid }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=valid::${{ github.event.client_payload.authentication == secrets.AUTH }}"
        id: valid_request
  preview:
    needs: [validate_run]
    if: needs.validate_run.outputs.valid_request == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Generate App Token
      uses: peaceiris/github-app-token@1.0.4
      id: app-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PEM }}
    - name: Find comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        issue-number: ${{ github.event.client_payload.pull_request }}
        repository: ${{ github.event.client_payload.repository }}
        body-includes: '## Deploy Preview'
        token: ${{ steps.app-token.output.token }}
    - name: Send/Update comment
      uses: peter-evans/create-or-update-comment@v2
      id: comment
      with:
        body: |-
          ## Deploy Preview
          
          Building Pull request preview. Please wait...
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.client_payload.pull_request }}
        token: ${{ steps.app-token.outputs.token }}
        edit-mode: replace
    - name: Checkout remote repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.client_payload.repository }}
        ref: ${{ github.event.client_payload.commit }}
    - name: Prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt
    - name: Build MkDocs
      run: mkdocs build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ steps.app-token.outputs.token }}
        publish_dir: ./site
        destination_dir: ./${{ github.event.client_payload.repository}}/${{ github.event.client_payload.pull_request }}
        full_commit_message: Push deploy preview from PR ${{ github.event.client_payload.pull_request }} in ${{ github.event.client_payload.repository }}
    - name: Delay Comment update
      run: sleep 30s
      shell: bash
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        body: |-
          ## Deploy Preview
          
          Deploy Preview successfull!
          *Make sure to try again in a few minutes if the below link gives you a 404*
          
          | Type    | Link                                                                                                                                           |
          | ------- | ---------------------------------------------------------------------------------------------------------------------------------------------- |
          | Commit  | ${{ github.event.client_payload.commit }}                                                                                                      |
          | Preview | https://gh-pages-deploy.github.io/Deploy-Previews/${{ github.event.client_payload.repository}}/${{ github.event.client_payload.pull_request }} |
          | Logs    | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}                                                            |
        comment-id: ${{ steps.comment.outputs.comment-id }}
        token: ${{ steps.app-token.outputs.token }}
        edit-mode: replace
    - if: ${{ failure() }}
      name: Update comment (Failed)
      uses: peter-evans/create-or-update-comment@v2
      with:
        body: |-
          ## Deploy Preview
          
          Deploy Preview failed!
          *The Deploy Preview for the Pull request couldn't be made. Please check the logs for details.*
          
          | Type    | Link                                                                                                 |
          | ------- | ---------------------------------------------------------------------------------------------------- |
          | Commit  | ${{ github.event.client_payload.commit }}                                                            |
          | Logs    | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}                  |
        comment-id: ${{ steps.comment.outputs.comment-id }}
        token: ${{ steps.app-token.outputs.token }}
        edit-mode: replace
