name: Deploy Preview

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: "The Pull request to target for the deploy-preview"
        required: true
        type: text
      authentication:
        description: "The secret to authorize this action run"
        required: true
        type: text

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=valid::${{ inputs.authentication == secrets.AUTH }}"
        id: valid_request
      - name: Run a one-line script
        run: "echo ${{ steps.valid_request.valid }}"
